language: node_js
node_js: '10'
cache: npm
env:
  - GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/UtahKoopServer-cb9863cc94b9.json
before_install:
  - openssl aes-256-cbc -K $encrypted_8d463ba1c33d_key -iv $encrypted_8d463ba1c33d_iv
    -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
install:
  - npm i
  - npm i -g serverless
script:
  - npm run test-travis
deploy:
  provider: script
  script: sls deploy
  skip_cleanup: true
  on:
    branch: master
  edge: true
notifications:
  email:
    on_success: change
    on_failure: change
