onlyBuiltDependencies:
  - esbuild
  - protobufjs
  - re2

overrides:
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  esbuild@<=0.24.2: '>=0.25.0'
  form-data@<2.5.4: '>=2.5.4'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  on-headers@<1.1.0: '>=1.1.0'
  tmp@<=0.2.3: '>=0.2.4'
  vite@<=5.4.19: '>=5.4.20'
  vite@>=5.2.6 <=5.4.20: '>=5.4.21'
