packages:
  - .

onlyBuiltDependencies:
  - esbuild
  - protobufjs
  - re2

overrides:
  qs@<6.14.1: '>=6.14.1'
  storybook@>=9.0.0 <9.1.17: '>=9.1.17'
  tar@<7.5.7: '>=7.5.7'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
