# Note:
# - This file enables pnpm "workspace mode". In workspace mode, the `packages` field is required
#   even for a single-package repo. We set it to `['.']` to declare the root as the only package.
# - We keep overrides here so they are considered during `pnpm install --frozen-lockfile` inside Docker.
#   This ensures the active config matches `pnpm-lock.yaml` and avoids
#   ERR_PNPM_LOCKFILE_CONFIG_MISMATCH during frozen installs.
packages:
  - .

onlyBuiltDependencies:
  - esbuild
  - protobufjs
  - re2

overrides:
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  esbuild@<=0.24.2: '>=0.25.0'
  form-data@<2.5.4: '>=2.5.4'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  on-headers@<1.1.0: '>=1.1.0'
  tmp@<=0.2.3: '>=0.2.4'
  vite@<=5.4.19: '>=5.4.20'
  vite@>=5.2.6 <=5.4.20: '>=5.4.21'
