service: serverless-print-proxy

provider:
  name: google
  runtime: nodejs
  project: utahkoopserver
  # the path to the credentials file needs to be absolute
  credentials: ${env:GOOGLE_APPLICATION_CREDENTIALS}

plugins:
  - serverless-google-cloudfunctions

# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  printproxy:
    handler: printproxy
    timeout: ${file(./config.json):TIMEOUT}s
    memorySize: 128
    events:
      - http: path
